# Generated by Django 6.0.3 on 2026-05-16 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('SINGLE', 'Single / EP'), ('ALBUM', 'Álbum de Estudio')], default='ALBUM', max_length=10)),
                ('fecha_lanzamiento', models.DateField()),
                ('portada', models.ImageField(upload_to='discografia/')),
                ('link_streaming', models.URLField(blank=True, help_text='Link a Spotify / Apple Music')),
            ],
        ),
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_principal', models.TextField()),
                ('imagen_perfil', models.ImageField(upload_to='about/')),
                ('link_instagram', models.URLField(blank=True)),
                ('link_youtube', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Biografía',
                'verbose_name_plural': 'Biografía',
            },
        ),
        migrations.CreateModel(
            name='Conciertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('link_tickets', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='merch/')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del producto')),
                ('stock', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('duracion', models.CharField(help_text='Ejemplo: 3:15', max_length=10)),
                ('numero_pista', models.PositiveIntegerField(default=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='core.album')),
            ],
            options={
                'ordering': ['numero_pista'],
            },
        ),
    ]
