# Generated by Django 6.0.3 on 2026-05-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('link_tickets', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Conciertos',
        ),
    ]
