# Generated by Django 6.0.3 on 2026-05-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_concierto_delete_conciertos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de archivo')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Video')], default='FOTO', max_length=10, verbose_name='Tipo de archivo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galeria/', verbose_name='Archivo de Imagen')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='Enlace de Video (YouTube)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galería',
                'verbose_name_plural': 'Galerías',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
