# Generated by Django 6.0.3 on 2026-05-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galeria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['-fecha_subida']},
        ),
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='tipo',
            field=models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], default='foto', max_length=10),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='url_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
