# Generated by Django 6.0.3 on 2026-05-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_galeria_options_alter_galeria_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=200, verbose_name='Nombre del Solicitante')),
                ('empresa_marca', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa o Marca')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de Contacto')),
                ('mensaje', models.TextField(verbose_name='Propuesta o Detalles del Evento')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
            options={
                'verbose_name': 'Contratación',
                'verbose_name_plural': 'Contrataciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
